openai_api_key = "<OPENAI_API_KEY>"
region = "us-west-2"
stage = "prod"
aws_config_path = "<HOME_DIRECTORY>/.aws/config"
aws_credentials_path = "<HOME_DIRECTORY>/.aws/credentials"
aws_profile = "<AWS_USER_PROFILE>"